### ISSUE TITLE
Controllers not working

### ISSUE THREAD

**Issue by smox2** [topher-au/WoWmapper#100]
I have tried xbox360 controller, PS4 controller and xboxone controller and they all seem to have an issue recognizing the left stick and buttons. Mapper recognizes all 3 controllers but still nothing any suggestions ? Am i missing an option somewhere ? Everything installed correctly on PC and console port opens correctly just can get left stick to work or buttons.

**Comment by seblindfors** [comment]
Run WM as admin. If it still doesn't work, untick `Send key binds directly to WoW` in WM.
