### ISSUE TITLE
Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by xelab1090** [topher-au/WoWmapper#105]
Are there any plans to integrate compatibility with this controller in the future and if so when would we be able to expect it? Right now nothing I have done gets WoWMapper to recognize it. Some of us don't have xbox/ps4/steam controllers.

**Comment by rbabjr** [comment]
You can probably set it up with Steam, using the Steam Controller template as a guide.

**Comment by matthenning** [comment]
Same issue here. Any news?

**Comment by seblindfors** [comment]
WoWmapper is not actively developed anymore. There will be no additional controllers added to the software.
