### ISSUE TITLE
no sensibility of the view

### ISSUE THREAD

**Issue by PatrickKranig** [topher-au/WoWmapper#107]
Hi, the addon has no setting for the sensibility of the controller for the view stick.

Kind regards

**Comment by seblindfors** [comment]
![image](https://user-images.githubusercontent.com/7464938/82353759-b2bb3e00-99b4-11ea-9a6c-312f3aa07950.png)

**Comment by PatrickKranig** [comment]
oh in the mapper! ok thanks ^^
