### ISSUE TITLE
WowMapper download didn't include an .exe

### ISSUE THREAD

**Issue by SamanthaLockwood** [topher-au/WoWmapper#108]
I'm trying to run World of Warcraft with a controller, because hey, why not? I've downloaded ConsolePort, and confirmed that WoW recognizes it. However, after attempting to download WoWMapper three different times, it became clear that it just wasn't including an .exe file. Without the executable file, I can't run WoWMapper, and so ConsolePort indefinitely tries to recognize my controller. 
![image](https://user-images.githubusercontent.com/67628783/86100347-b3042a00-ba86-11ea-9b0c-33f35d3dd213.png)

I downloaded it directly from GitHub, the most recent release, so I'm not sure what the problem is. I have the latest version of DirectX, and I'm sure everything I need is up to date. There's just no .exe file to be found.

**Comment by SamanthaLockwood** [comment]
There isn't an .exe file in any of the folders, either, before that is suggested.

**Comment by AndreasDellrud** [comment]
> There isn't an .exe file in any of the folders, either, before that is suggested.

Hi! You seem to have downloaded the code repository, not the compiled release. The actual binary can be found [here](https://github.com/topher-au/WoWmapper/releases/tag/8.3.0)
