### ISSUE TITLE
Blizzard recently banned broadcasted/simulated input 

### ISSUE THREAD

**Issue by pharrowboy** [topher-au/WoWmapper#115]
Hi, just figured I'd make a topic on this. Can anyone confirm if wowmapper is safe to use since the Ban?

Wowmapper uses simulated input that broadcasts virtual keys to the wow client
I figured that out by reading the code. 

This is the The kind of thing blizzard just banned. I'm thinking its not safe to use anymore. Maybe someone can confirm?

**Comment by seblindfors** [comment]
It doesn’t ”broadcast” anything. It sends a single 1:1 input to output ratio to the foreground window through Windows, or directly to the client if it’s detected.
