### ISSUE TITLE
every face button opens my bags

### ISSUE THREAD

**Issue by Cannier** [topher-au/WoWmapper#119]
Ive went through the intial setup for wowmappper and consoleport multiple times and i can't fix this issue :(

**Comment by thiagomaia971** [comment]
Same issue

**Comment by thiagomaia971** [comment]
Hi, I fixed by exiting the WowMapper, I'm using the PS4 controller, so I just run DS4Windows application and WoW, so worked fine, but yesterday I was playing with DS4Windows running and the Wowmapper too, but today, just running DS4Windows worked
