### ISSUE TITLE
Enhanced Interaction offset error

### ISSUE THREAD

**Issue by Wiebbe** [topher-au/WoWmapper#12]
Hey there,

It seems there was a small World of Warcraft patch because WoWMapper is telling me the offsets for WoW are wrong.

![schermafdruk 2016-01-08 23 17 12](https://cloud.githubusercontent.com/assets/480918/12210968/1f6b750e-b65e-11e5-83a2-de7914db4ad8.png)

**Comment by topher-au** [comment]
You can edit offsets file with the new build number - offsets are the same,
haven't update them yet

**Comment by topher-au** [comment]
This issue has been closed. As version 0.5 is a complete rewrite of previous versions, this issue should be resolved. If you have further troubles with 0.5 or higher, please open another issue.
