### ISSUE TITLE
Does not read my 360 controller that is connected thru usb port

### ISSUE THREAD

**Issue by Sjlazy** [topher-au/WoWmapper#14]
when i click the plugins it gives me the regular option of the "DualShock4" and the "Xbox Controller" , ive tried both . after shouldn't it automatically connect to the controller since it is connect through the usb port . i log in to wow and it gives me the option of the control followed by the direction to click the button "y" but my controller isnt reacting to any buttons . How can i fix this?

**Comment by seblindfors** [comment]
In the current release, you have to restart the program when you change plug-in. This might solve your issue. Beyond that, you need to make sure you have the proper drivers installed for your controller.

**Comment by topher-au** [comment]
This issue has been closed. As version 0.5 is a complete rewrite of previous versions, this issue should be resolved. If you have further troubles with 0.5 or higher, please open another issue.
