### ISSUE TITLE
Orginial Issue

### ISSUE THREAD

**Issue by Kyle757** [topher-au/WoWmapper#16]
Everything works fine until I'm in the game.  Then I get this screen and when I press buttons on my controller nothing happens.
![img_0146](https://cloud.githubusercontent.com/assets/16599745/12528465/6200758e-c164-11e5-8f61-30aa1dd9aec3.JPG)

**Comment by topher-au** [comment]
Greetings! Does the main application window show "World of Warcraft is running"? If not, that means it's not detecting WoW for some reason. Try manually setting the Architecture Type under WoW settings and see if that helps.

**Comment by Kyle757** [comment]
It says World of Warcraft is running.

**Comment by topher-au** [comment]
Hey there,
It's weird that it's detecting the game but it's not receiving keypresses. Are you running WoW as Administrator by any chance?

Anyway, I have included some basic debug logging features in version 0.5.0.2. Please install it and enabled logging from the WoWmapper settings page, then restart the application. The output will be called "log.txt" in the same folder as WoWmapper, and you can view it by clicking "View log file" on the settings page.

Please try this and send me the log output.

Thanks

**Comment by Kyle757** [comment]
Hey, I'm running it as administrator.  I'm not able to update to 0.5.0.2.  When I attempt to download it WoWmapper crashes.

**Comment by topher-au** [comment]
That might be the issue, try running WoWmapper as admin

**Comment by Kyle757** [comment]
I am running it as admin.

**Comment by topher-au** [comment]
I suspect that may be part of the issue. I have been able to reproduce the bug when running WoW as admin and WoWmapper as a regular user, but when running both as Admin it worked fine. Can you confirm that you are running both applications as Admin?
If this is the case there is little I can do, non-elevated applications cannot interact with elevated ones, you will need to run both as Admin, or neither (the second is preferable!)

**Comment by justdiferent** [comment]
So I'm having problems installing the wowmapper application, when i run the setup wizard and select Run program, it does nothing but close the wizard... And when I manually go in to open it, it says something about 'something went wrong in the xbox driver'. Upon watching some videos about wow mapper and console port it looks like I might be missing files or have different files? Whats going on?

**Comment by topher-au** [comment]
Hey there, please check that you have DirectX 9.0c installed, it can be downloaded from the main page. Thanks!

**Comment by Entropycheck** [comment]
Wowmapper not detecting Classic as of 1/30/2019
tried all troubleshooting steps listed above
