### ISSUE TITLE
WoWmapper keybinds

### ISSUE THREAD

**Issue by HungryNoodle** [topher-au/WoWmapper#17]
Crashes when trying to change keybinds through WoWmapper.

**Comment by topher-au** [comment]
Do you have WoWmapper installed into Program Files by any chance? Please try version 0.5.0.3 at let me know if that fixes the issue.

**Comment by HungryNoodle** [comment]
My WoWmapper is installed in LocalAppData currently. I've updated and the issue still arises when trying to change keybinds.

**Comment by topher-au** [comment]
I see, thanks for your response. I'll look into what is causing the other issue.
