### ISSUE TITLE
wowmapper failing to install

### ISSUE THREAD

**Issue by pyroflesh** [topher-au/WoWmapper#18]
Downloaded the latest version (0.5.0.3) and trying to install via the installer. When clicking on the installer, i get all regular UAC pop-ups, then nothing happens. Upon opening task manager i see the following:
![capture](https://cloud.githubusercontent.com/assets/5867374/12580736/b09f03c4-c47d-11e5-99b7-5563a4f3e6c6.PNG)

One of these tasks was closeable, to close the others required a restart.

EDIT: in trying various other methods to install this, i managed to install version 0.4.1. Clicking update in this version caused wowmapper to hang, and similar tasks to open in task manager. Running Windows 7, latest update (as of 26/01/2016).

**Comment by topher-au** [comment]
Hmm! Strange, the installer isn't one I made myself so it's hard to debug. At this stage I can only recommend you ensure all instances of the installer are closed, re-download the installer and try again. Let me know if this helps.

**Comment by pyroflesh** [comment]
This issue seems to have sorted itself, tried again today and everything worked fine. Not having much of an idea how github works, i couldn't figure how to close this issue.

**Comment by topher-au** [comment]
Cool, hoped that would work out :)
