### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by mikelowry007** [topher-au/WoWmapper#19]
i have downloaded the exe. installed it, try to open it, i get a crash

driver disabled
an error occured with with the xbox driver, and it has been disabled
the erroe was;
unable to load DLL 'xinput1_3.dll' the specified module could not be found

**Comment by topher-au** [comment]
Hi, it seems you do not have the appropriate version of DirectX installed.

Could you please do the following:
1. Press Windows Key + R
2. Enter DxDiag into the dialog that opens and press enter
3. Press "Save All Information" and either upload the output file or paste it here

**Comment by topher-au** [comment]
Greetings once again.

It seems Windows 10 doesn't include the older xinput dll's, thus requiring you have DirectX 9.0c installed.

[You can download it here]
(https://www.microsoft.com/en-us/download/confirmation.aspx?id=8109)

The newest app and installer now both check for the existence of DirectX 9.0c before starting up, thanks for your feedback.
