### ISSUE TITLE
wowmapper crashes

### ISSUE THREAD

**Issue by pyataku** [topher-au/WoWmapper#20]
Hey.
Wowmapper crashes after pressing any button exept right stick and left stick click on xbox 360 controller. But it happens only before wow launched. Then wow launched everything works fine.

![wowmapper1](https://cloud.githubusercontent.com/assets/17029464/12756426/cb9f1f9e-c9e4-11e5-881c-5590872b0079.jpg)

**Comment by milocamus** [comment]
I have the same issue! I did a dxdiag and i have version 12. Plus once inside wow the game creates lua errors when I try bind keybindings

**Comment by topher-au** [comment]
If you're getting LUA errors in-game, then you'll have to follow that up with the respective addon author - all my app does is send the keypresses as if you were using a keyboard/mouse.

I will look into what is causing the crashes when WoW is not running, as long as it works in-game for now that is satisfactory :)

**Comment by topher-au** [comment]
Issue #20 should be resolved as of 0.5.1.0
