### ISSUE TITLE
OSX wowmapper

### ISSUE THREAD

**Issue by MichalNemec** [topher-au/WoWmapper#21]
hi,

will be there any wowmapper for osx?

thanks

**Comment by topher-au** [comment]
Hello,

No plans at this stage, sorry. You can still use ConsolePort, but you will need to use ControllerMate or Joystick Mapper.

**Comment by MichalNemec** [comment]
the thing is, that i dont know how to map it into buttons. i thought wowmapper does it itself, bud joystickmapper doesnt

**Comment by topher-au** [comment]
Have a look in the ConsolePort folder, I believe there are some example
profiles you can use in there.

On Wed, Feb 17, 2016 at 10:46 AM, MichalNemec <notifications@github.com>
wrote:

> the thing is, that i dont know how to map it into buttons. i thought
> wowmapper does it itself, bud joystickmapper doesnt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topher-au/WoWmapper/issues/21#issuecomment-184927997>.
>



-- 
Thankyou,
Chris Sheridan <lordramza@gmail.com>
