### ISSUE TITLE
WoWmapper doesnt work

### ISSUE THREAD

**Issue by Tyrandel** [topher-au/WoWmapper#22]
So I downloaded the program and when I tried to open it, it wouldn't pop up. All there was that signified it was running for a second is the icon on the bottom right corner. It occasionally will appear in the task manager for a long period of time but doesnt do anything. I've tried the compatibility versions and nothing worked. There's no anti virus softwares interfering and I have tried earlier versions both msi and zip. Can someone help me?

**Comment by g-viana** [comment]
I had this same problem, the application wouldn't pop up at all. What I did was install version 0.4.4, which works, and them update it. It seems the plugins folder isn't included on versions 0.5.x
