### ISSUE TITLE
Help Topher

### ISSUE THREAD

**Issue by ArkaelDren** [topher-au/WoWmapper#23]
Hey buddy, I just started playing wow again thx to this specific consoleport and wowmapper.  Seems as though since this last patch yesterday March 22nd 2016 the advanced features of wowmapper are not available. I use these features to invert my Vertical control and now that I have started using this addon, I cant go back lol. I'm disabled so using a keyboard is a bit difficult so with a controller I can actually play again.

Thank you for this, I cant even begin to express how cool it is to be able to play again.

**Comment by topher-au** [comment]
Hey there,
There is an invert controls option inside World of Warcraft you can use, it
is located in interface settings->camera

**Comment by ArkaelDren** [comment]
Thx bud, didn't know that was available.  Feel a bit foolish, but whats up with the advanced features no longer working, did it have something to do with the patch?  I'm sure you will get around to updating because I have seen multiple updates just during the one month I have been using your Adds.  Again, I want you to understand what your addon has done for me.  I know it might not seem like a big deal, but your helping an old disabled Dad that has missed Wow since my injuries. 

    On Wednesday, March 23, 2016 10:17 PM, Topher Sheridan <notifications@github.com> wrote:
 

 Hey there,
There is an invert controls option inside World of Warcraft you can use, it
is located in interface settings->camera

**Comment by ArkaelDren** [comment]
Ok man, even more foolish.  Interface/Mouse/Invert fucking box check...  lol
 

    On Wednesday, March 23, 2016 10:17 PM, Topher Sheridan <notifications@github.com> wrote:
 

 Hey there,
There is an invert controls option inside World of Warcraft you can use, it
is located in interface settings->camera
