### ISSUE TITLE
Xbox 360 triggers as Ctrl/Shift modifiers

### ISSUE THREAD

**Issue by b1991** [topher-au/WoWmapper#24]
Hi there,

I have successfully installed wowmapper and enabled my xbox 360 controller to work through it, however I am wanting to make the left trigger as [ctrl], and the right trigger as [shift], so they can act as modifiers, for abilities which I have placed on my bottom left action bar and bottom right action bars, respectively (I have assigned key bindings to them, i.e. Ctrl+1 to the first slot on the bottom left action bar and so on, as shown in the image). 
I have my main abilities on the main action bar, and I can use these abilities fine with the xbox 360 controller, but when I try to use the triggers as modifiers it does not work - note that I am not using the advanced 'trigger grip' feature since advanced features are currently disabled. However I have tested the triggers as main action bar buttons and they do work.

Any help would be greatly appreciated.

![wowmapper controller](https://cloud.githubusercontent.com/assets/18152914/14125205/d6543f2a-f601-11e5-9578-4c5cac9201c4.PNG)

**Comment by seblindfors** [comment]
Any reason why you're not using ConsolePort?

**Comment by b1991** [comment]
I should add that I am playing on a vanilla server - 1.12.1 - I tried using consoleport but it does not work on that version (comes up with a UI error window) and I couldn't find an earlier version that worked (if there is one please direct me to it), so until I can find a way of using wowmapper to work with triggers as modifiers i'm at a loss since using a controller is only viable if I can do that really.
If you have any suggestions of how else that could be done that'd be great too.

**Comment by topher-au** [comment]
Greetings,
I cannot offer any support for older versions of WoW as WoWmapper is designed to work with the retail version of the game. You will need to manually configure another controller mapper for better support.
