### ISSUE TITLE
xbox one support windows 10

### ISSUE THREAD

**Issue by ragar91** [topher-au/WoWmapper#25]
I have been having issues getting xbox one controller to detect. Worked for a second but now i get nothing. wowmapper will not detect that the xbox one controller is connected

**Comment by bwtipton123** [comment]
seconded... sooo..???

**Comment by topher-au** [comment]
Have you installed DirectX 9.0c? It needs to be installed for proper controller support currently. It can be installed alongside the most recent version of DirectX and you can find the link on the main page.
