### ISSUE TITLE
Unable to uninstall on Windows 10.

### ISSUE THREAD

**Issue by ranste** [topher-au/WoWmapper#3]
I got WoWmapper working with Console Port for Warcraft on my second computer which I use as a test computer for all addons first and was attempting to remove everything before moving to my main computer. Everything else came off the computer with ease, however WoWmapper just hangs when I attempt to uninstall.  If you have any fixes please let me know.

**Comment by topher-au** [comment]
Hmm, interesting one. I can only suggest you remove the files manually (%LocalAppData%\WoWmapper) and then attempt to uninstall which should remove the entry from the programs list. No other files are installed or modified outside of this directory.

**Comment by ranste** [comment]
I removed everything and it still stays in the list of installed files. I'm not too worried, but if it ends up being an issue for others hopefully a fix is found. Thank you for the response.
