### ISSUE TITLE
Support for multiple modifiers on a single button

### ISSUE THREAD

**Issue by TonyPhipps** [topher-au/WoWmapper#30]
I would love to use the following setup, but it appears WoWMapper only supports one modifier per button.
LTrigger - Control
RTrigger - Shift
LBump - Control+Shift
RBump - Control+Alt

**Comment by topher-au** [comment]
Since WoWmapper is designed to be used with ConsolePort, this is not particularly high on the priority list, however I will try and keep it in mind when I write the Keybinding code for version 7.0 (coming soon(tm))

**Comment by TonyPhipps** [comment]
Thanks for your consideration.
