### ISSUE TITLE
wow not running

### ISSUE THREAD

**Issue by Jessyahnke** [topher-au/WoWmapper#32]
Ever since the patch came out wowmapper says wow is not running when I am playing. 
Any suggestions? I already changed the in wowmapper from auto detect to 64-bit

**Comment by CrtAurelien** [comment]
Hey man!

I did the same shit... but i resolved it! You should go in C:\Program Files (x86)\World of Warcraft or your path & launch WoW and not WoW64. 

Feedback & good luck!
