### ISSUE TITLE
Not auto centering after mouse look

### ISSUE THREAD

**Issue by 3MBD** [topher-au/WoWmapper#34]
I don't know what it is, its like the 'Advance Feature' isn't working at all for me.
i can live with the 'no' vibration , but the 'auto center' i really need it.
i tried uninstalling reinstalling the .Msi file with a 'Fulll' install,  new clean install for Windows, clean install Consoleport, open as 'Admin'
basiclly everything i could think of. But nothing worked ='( 
Is there anything i'm missing? I'm running Wowmapper 6.0.4 with a PS4 Controller.µ

EdIt: running all the drivers that is needed on Windows 10

**Comment by topher-au** [comment]
Please try with 7.1.6 and reopen the issue if it is not resolved.
