### ISSUE TITLE
WoWmapper won't start because it thinks an instance is already running

### ISSUE THREAD

**Issue by hamc09** [topher-au/WoWmapper#35]
What it says on the tin. First-time user of the program, never installed before. I originally used the installer, and when trying to run the program it insisted it was already running, even though I can't see it anywhere in the Task Manager's Details pane. Tried uninstalling (which doesn't actually remove the software for some reason) and just downloading the non-installing archive, same problem. Restarts, Windows updates, nothing fixes it.

**Comment by hamc09** [comment]
Tried the previous version (0.6.0.4) and had no issues.

**Comment by hamc09** [comment]
Not yet fixed in 7.0.1.

**Comment by topher-au** [comment]
Greetings. From version 7.1.3 onwards you will be able to start the application with the --ignore-mutex parameter and it will try to ignore any other instances. I can't imagine why this is happening except that another application shares mutex ID with WoWmapper, which while unlikely is not impossible.

**Comment by Cloud308** [comment]
Having the same issue repeatedly getting "Another instance of WoWmapper is running, after downloading and trying to run it - how do you start with the ignore-mutex parameter

**Comment by a12238999** [comment]
how do you start the application with the --ignore-mutex parameter
