### ISSUE TITLE
Unable to uninstall WoWmapper. Crashing at launch of WoW.

### ISSUE THREAD

**Issue by FamilyGamester** [topher-au/WoWmapper#36]
I came back to WoW and wanted to update WoWmapper and Consoleport. However, I couldn't figure out how to uninstall the old version of WoWmapper. I couldn't update WoWmapper through the app itself, but I also couldn't find any way to uninstall the old one. It doesn't appear in install/uninstall under control panel or even in program files. Is WoWmapper just an executable that doesn't actually install itself?

So anyway, I downloaded and ran the newest version of WoWmapper. It picks up my 360 controller, but shows it as a generic Xinput. Is this correct? Also WoWmapper crashes and displays a "is not responding" error whenever WoW is launched. Is this due to not properly uninstalling the old version? Or do I need to adjust a setting like enabling Memory Reading? Do I need to enable Memory reading anyway due to ConsolePort?

**Comment by topher-au** [comment]
Please try with 7.1.6 and reopen the issue if it is not resolved.
