### ISSUE TITLE
Keybinds keep resetting after wowmapper update changes

### ISSUE THREAD

**Issue by aidenXchaos** [topher-au/WoWmapper#37]
Everytime wowmapper changes because of a update my keybindings get changed and then i have to freaking go fix the damn thing every single time and it pisses me off cause i have to figure out how to set back up the keybinding. I's so use to using the controller to play WoW and so these keybinding reset updates really screws me over. [edit1]Ok i have found a set up that is kinda what im use to Triggers (L2 + R2) but for some reasons i cant switch the left trigger and the right trigger because in game thats the way they were. [edit2] Ok i have found a way around the problem by switching my abilities on hot bar by switching everything on the right trigger with the lift trigger so now everything works the same way it was before the update but this is still an issue that needs to be fixed because the next keybind reset update everything will be all screwed up again....

**Comment by topher-au** [comment]
How do you have the application installed? The keybinds are stored in keybinds.xml in the installation directory. Is there a reason the default bindings don't work for you? If you leave the defaults ConsolePort will import and set them up for you automatically, then you only need to set up the ConsolePort bindings in game.
