### ISSUE TITLE
DirectX12

### ISSUE THREAD

**Issue by Joeac** [topher-au/WoWmapper#38]
I have recently built a new PC that is dx12 and it states that this program is now incompatible. Is this the case ? I can get the program to download but isn't in the program files. Additionally when I try and start the program it will show the icon in the app screen an then close out immediately.  I am using the installer to install the program am I doing this incorrectly?

**Comment by topher-au** [comment]
I suspect it's some kind of automatic checking that Microsoft is doing. If you have Windows 10, it should have DirectX 10 (or a compatible driver) installed already. If it's crashing out immediately, there's probably something else wrong. Have a look at log.txt in the application directory.

If you installed to the default location, you can access the folder by pressing Windows and typing Run, then press Enter. Then type "%LocalAppData%\WoWmapper" (without the quotes) and press Enter. This should show you where it is installed.

**Comment by aidenXchaos** [comment]
I am having the same problem I just recently did a factory reset and now wowmapper is installed but will not run and is incompatible. I checked the system requirements and found i have DirectX12 which is above requirements.

**Comment by aidenXchaos** [comment]
I just installed DirectX10 and now wowmapper is running good. I'm guessing wowmapper isnt compatible with DirectX12
