### ISSUE TITLE
Crashes After 5-10 Mins 

### ISSUE THREAD

**Issue by mba94** [topher-au/WoWmapper#45]
Hello there. Great work on this program, I have been enjoying it for about a year problem free on my old Windows 7 computer. However, over the weekend I upgraded to a new Windows 10 computer and can't seem to fix this problem. 

WoWmapper now always crashes after about 5 to 10 minutes. It works fine up until that point. It doesn't matter if I'm in WoW or if I simply have WoWmapper open on the desktop and nothing else. It doesn't matter if I am using the controller or if I have the controller on but I'm not touching it. I will still get the “WoWmapper has stopped responding” message after about 5 to 10 minutes. 

Here is what I have tried: (Note that I am using the current version of both WoWmapper and ConsolePort.)
* I have attempted to use WoWmapper with the Xbox button on, the Xbox button off, and the Xbox app completely uninstalled the via PowerShell. 
* I have tried using WoWmapper with both a wireless Xbox 360 controller and a wired Xbox 360 controller (Windows says I have the latest drivers for both). 
* I have tried all 3 versions of SlimDX.
* The DLL have all the permissions they need, from what I can tell. I don't see any option to add additional permissions. 
* I have tried running WoWmapper in compatibility mode. 
* I am running WoWmapper as administrator. 

No matter what, the crash will happen consistently after 5 to 10 minutes. 

Do you have any idea what I am missing here? I would love to get the program up and running so I can enjoy WoW with a controller as I have previously. Thanks!

**Comment by topher-au** [comment]
Could you see if the issue persists with the latest version? Thanks

**Comment by mba94** [comment]
Looks like that fixed it! Thanks!
