### ISSUE TITLE
WoWmapper has stopped working

### ISSUE THREAD

**Issue by dmalcom09** [topher-au/WoWmapper#46]
Latest version wont launch at all what could I be doing wrong T.T

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	WoWmapper.exe
  Problem Signature 02:	7.1.5.0
  Problem Signature 03:	57d823ba
  Problem Signature 04:	WoWmapper
  Problem Signature 05:	7.1.5.0
  Problem Signature 06:	57d823ba
  Problem Signature 07:	53
  Problem Signature 08:	17
  Problem Signature 09:	System.DllNotFoundException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	f041
  Additional Information 2:	f041bfcff05ac48ac82192bec887662e
  Additional Information 3:	558e
  Additional Information 4:	558e5b0658b5ce0fff5f51548df5f073

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by dmalcom09** [comment]
[3:33:04 PM] Controller manager starting up...
[3:33:04 PM] Searching for DS4 controllers...
[3:33:04 PM] XInput interface starting up
[3:33:04 PM] Loading XInput 10 wrapper...
[3:33:04 PM] Failed to load XInput 10 wrapper!
[3:33:04 PM] Registered for USB events with handle [1BBF5930]

**Comment by topher-au** [comment]
Please try with 7.1.6 and reopen the issue if it is not resolved.
