### ISSUE TITLE
wow mapper has stopped working

### ISSUE THREAD

**Issue by leoncole** [topher-au/WoWmapper#47]
My wowmapper will not open, just got this today. 
Problem Event Name:	CLR20r3
  Problem Signature 01:	WoWmapper.exe
  Problem Signature 02:	7.1.5.0
  Problem Signature 03:	57d823ba
  Problem Signature 04:	WoWmapper
  Problem Signature 05:	7.1.5.0
  Problem Signature 06:	57d823ba
  Problem Signature 07:	53
  Problem Signature 08:	17
  Problem Signature 09:	System.DllNotFoundException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	f041
  Additional Information 2:	f041bfcff05ac48ac82192bec887662e
  Additional Information 3:	9f07
  Additional Information 4:	9f074dd2737b55b81c244754bb206b7c

**Comment by topher-au** [comment]
Please try with 7.1.6 and reopen the issue if it is not resolved.

**Comment by leoncole** [comment]
I fixed the issue for my self downloading the version before this latest of wow mapped thank you very much for a great product
