### ISSUE TITLE
XBOX 360 Issue

### ISSUE THREAD

**Issue by RoF-Josh** [topher-au/WoWmapper#5]
Hello there! First off let me just say this programme is amazing, If only i didn't have this issue, I've searched far and wide for a fix but nothing seems to work. 

The installation went very smoothly, no issues at all - I have downloaded the latest version of SlimDX from the source you provided ( I have tried both ) - Consoleport is installed and I've disabled my guide button.

For some reason when I'm in game it doesn't recognize any of my button presses ( yes WoWmapper is running ).

I've reinstalled numerous times, rebooted my PC after installing, reinstalled the drivers for my controller... you name it, nothing works.

Any help would be greatly appreciated.

-Josh

**Comment by seblindfors** [comment]
Just making sure you remembered to select the Xbox profile, since Dualshock 4 is running by default:
![66fab187dd9dd02b1cd2b8c7f584238b](https://cloud.githubusercontent.com/assets/7464938/12069924/d80ef7ae-b053-11e5-8504-248e8dce050f.gif)

**Comment by topher-au** [comment]
G'day!

As Seb mentioned above, you will need to select the appropriate driver for the controller to show up as connected. Additionally, under Windows 7 you will need the Xbox 360 controller driver installed. If you have the controller showing up in the Windows controller configuration as an Xbox controller, WoWmapper should detect it automatically.

**Comment by RoF-Josh** [comment]
Yes the profile is checked, and as stated above I do have the latest version installed.

I tried all everything i could think of before making the post, hense why I'm asking for help. :)

**Comment by topher-au** [comment]
Hey there, would you kindly submit a copy of your DxDiag output.

Enter "dxdiag" into the run prompt from the start menu and choose "Save all information" then upload the text document or email it to me at lordramza@gmail.com

This is the driver you need installed:
https://www.microsoft.com/hardware/en-au/d/xbox-360-controller-for-windows

Is the app telling you no device is connected at all, or is it showing that is connected, but no output to the game? Also, are you running WoW in 64-bit (that's the default) or 32-bit mode?

**Comment by RoF-Josh** [comment]
Email is sent, hope it helps. :)

Yes that is the driver i already have installed - I reinstalled the link you sent me just to make sure but it hasn't changed anything.  I am running WoW in 32-bit mode on 64-bit windows 7 because i'm on a pretty ancient laptop and it really needs those spare resources. :P

Here is a link to what the app is telling me.

' [img]http://i.imgur.com/pDUe7qt.png[/img] '

**Comment by RoF-Josh** [comment]
Resent the email you requested.

**Comment by RoF-Josh** [comment]
Ok so I've got myself all worked up over not being able to figure this out, so i reinstalled Xpadder / button on guide2 and everything is working fine, without any issues at all - no idea what I'm doing wrong here... :/

**Comment by RoF-Josh** [comment]
Okay so followed this tutorial since I am running a RockCandy Xbox360 controller instead of the official microsoft controller: https://www.youtube.com/watch?v=yCYN_2Ia0zQ

So my drivers are now following a different path as before which is:

xbox360>setup64>files>driver>win7

_________________

I am now recieving this error message when i open WoWmapper:

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at WoWmapper.MainForm.InitializePlugin(String DllFile)
   at WoWmapper.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at WoWmapper.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WoWmapper
    Assembly Version: 0.4.2.0
    Win32 Version: 0.4.2.0
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapper.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
WoWmapper_Input
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapper_Input.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

____________________

I am also receiving this error message when I click plugins to change to the xbox 360 setting:

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at WoWmapper.PluginSelectForm.RefreshInputPlugins()
   at WoWmapper.PluginSelectForm..ctor()
   at WoWmapper.MainForm.buttonSelectPlugin_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WoWmapper
    Assembly Version: 0.4.2.0
    Win32 Version: 0.4.2.0
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapper.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
WoWmapper_Input
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapper_Input.DLL
----------------------------------------
WoWmapperEI
    Assembly Version: 0.3.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapperEI.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by RoF-Josh** [comment]
I am also receiving this error message when I click plugins and try to change to the xbox 360 setting (it won't allow me to select anything or access the drop down menu):

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
at WoWmapper.PluginSelectForm.RefreshInputPlugins()
at WoWmapper.PluginSelectForm..ctor()
at WoWmapper.MainForm.buttonSelectPlugin_Click(Object sender, EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

WoWmapper
Assembly Version: 0.4.2.0
Win32 Version: 0.4.2.0

CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapper.exe

System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Newtonsoft.Json
Assembly Version: 7.0.0.0
Win32 Version: 7.0.1.18622

CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/Newtonsoft.Json.DLL

System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

WoWmapper_Input
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0

CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapper_Input.DLL

WoWmapperEI
Assembly Version: 0.3.0.0
Win32 Version: 1.0.0.0

CodeBase: file:///C:/GAMES/Xbox360%20Controller/WoWmapper/WoWmapperEI.DLL

System.Numerics
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
Assembly Version: 4.0.0.0
Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

**Comment by RoF-Josh** [comment]
I'll stress again my controller works fine with Xpadder, so I don't believe it's a driver issue as you guys seem to think, but you're the experts so i'm just following your advice here. 

Would you like to contact me via skype or anything similar so we can get this figured out? :)

**Comment by topher-au** [comment]
That error is usually caused by the DLL files being blocked - if you
re-extracted the zip then the files may have been blocked again - just
unblock them from the properties window again. Sorry there's not much of a
way around this as it's a windows "feature"

**Comment by RoF-Josh** [comment]
Yeah It's not been re-extracted, and as you can see from this link it's already been unblocked (Given the fact the option isn't there anymore.) le sigh.. xD

http://i.imgur.com/5sp4AQ6.png

**Comment by RoF-Josh** [comment]
Just a bit more proof:

http://i.imgur.com/XZdKvdw.png

I'm starting to feel like an idiot even though I'm sure I'm doing this correctly...

**Comment by seblindfors** [comment]
The DLL files are located in the "plugins" subfolder where you installed WoWmapper.
From your screenshot I'm guessing you have them at:
C:\GAMES\Xbox360 Controller\WoWmapper\WoWmapper\plugins

If using the default install location with the installer, you should find the plugins by finding the appdata directory, by clicking Ctrl+R and entering this:
%AppData%\..\Local\WoWmapper\plugins

Check properties of both input_360.dll and input_ds4.dll and make sure they don't have this tickbox:
![image](https://cloud.githubusercontent.com/assets/7464938/12080485/f6f02508-b25b-11e5-833b-39fafb1e713c.png)

**Comment by RoF-Josh** [comment]
Okay got that sorted, thank you very much.

Unfortunately this still does not work in game - I'll wait for the update you were talking about Topher and give you feedback when i can - thank for your patience guys, let's see if we can get this fixed together. ;)

**Comment by RoF-Josh** [comment]
Alright that got WoWmapper working without any issues, thanks for that - still does not work in game though unfortunately, I'll wait for this update you were talking about Topher and see where it goes from there. :)

**Comment by topher-au** [comment]
Hey mate,

Try updating to 0.4.3 and tell me if that fixes the issue? Let me know.

Thanks,
Topher

On Mon, Jan 4, 2016 at 11:07 AM, RoF-Josh <notifications@github.com> wrote:

> Alright that got WoWmapper working without any issues, thanks for that -
> still does not work in game though unfortunately, I'll wait for this update
> you were talking about Topher and see where it goes from there. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topher-au/WoWmapper/issues/5#issuecomment-168556835>.
>



-- 
Thankyou,
Chris Sheridan <lordramza@gmail.com>

**Comment by RoF-Josh** [comment]
It worked! Theres one slight issue, it seems to invert my controller since the update - there was also a consoleport update which may have done that, but its an easy fix i just set the keybinds the opposite way around. 

But the controller is -- working -- we did it boys! ;)

Thank you for your patience.

**Comment by RoF-Josh** [comment]
Do you plan on ever doing chatpad support? I'm not a huge fan of conesole ports way of typing i find it very slow compared too a chatpad.

**Comment by topher-au** [comment]
Well it could be possible - I haven't got one to try it out but somewhere
down the line I will look at adding support. Have a lot of other changes in
the pipeline before I can get to that though.

**Comment by RoF-Josh** [comment]
Just good too know you're working on it, thanks dude that's very good news! :) and a big thanks for that fix - I'll let you know if i encounter any more problems in the future.
