### ISSUE TITLE
OSK Design Suggestion

### ISSUE THREAD

**Issue by CyberFoxHax** [topher-au/WoWmapper#50]
I have no issues. But I saw this project had an special keyboard for quickly writing messages and stuff. I have a similar project and have juts recently been working on a design that resembles the Glyphs screen in WoW.

If interested I can send you the .psd
https://github.com/CyberFoxHax/ControllerOSK

Either way you can just close this issue. Thank you!

**Comment by topher-au** [comment]
Well, that's actually quite pretty! I'm not sure I'm ready to implement another large scale feature into WoWmapper right now, but I really like what you've done and that artwork is great!
