### ISSUE TITLE
How to play standart USB Gamepads?

### ISSUE THREAD

**Issue by Rettosoft** [topher-au/WoWmapper#51]
Greetings.
I not have any pads. But have USB standart game pad. 
How to play it?

**Comment by CyberFoxHax** [comment]
You have a pad or not? A tad more info would be nice.

I'm assuming you have an old controller. That means it is probably not going to run on XInput. I'm not the developer in this project, but just looking at the code there is only implementations for the PS4 Controller and XInput. Afaik DS4 uses DirectInput or more precisely, their own standard. That's irrelevant.

Your controller, if not XInput then it's probably juts a classic DirectInput. Your best guess would be to remap your DirectInput device to XInput, there exists wrappers that can help you do this easily.
For example this: https://github.com/Stents-/XOutput/releases

Being a controller-computer user is hard work.
~Foxxy

**Comment by topher-au** [comment]
Greetings, it's not a feature to use a generic USB controller, but it has been requested a few times and is definitely something I will be looking into going forwards.

In the mean time, you can use some other software to emulate an Xbox controller, then have WoWmapper use the virtual controller as it's input.
