### ISSUE TITLE
.dll files are not present in the installer or .zip folder

### ISSUE THREAD

**Issue by KriticalHit** [topher-au/WoWmapper#52]
I was super excited to learn about WoWmapper and the possiblity of playing with a controller, but unfortunately it is crashing for me too. I have the necessary .NET framework and the other addons, but it does not get past the "WoWmapper has stopped working" error box after a second of being open. I saw in an earlier thread you said this:

Hey there, can you please check that input_ds4.dll exists in the plugins folder, usually located at

C:\Users<your user name>\AppData\Local\WoWmapper

If it's not there, download the .ZIP archive from the latest version and drop the plugins into the plugin folder - even if you're using a 360 controller, the default is DS4, so they both need to be present initially.

However, when I searched for that folder on my computer, the .dll files were not present. Also, those files are not present in the latest version, or any version, of the .zip collections I've downloaded. Where do I get these files?

EDIT: I also should add that there is no "plugins" folder in the pathway you listed either.

**Comment by topher-au** [comment]
That's for a very, very old version of WoWmapper. It's since been fully reworked to not require any input plugins. If you could post the log file (log.txt) next time you launch the program that would be excellent.
