### ISSUE TITLE
WoWmapper.exe run and close instant

### ISSUE THREAD

**Issue by lolopsycho** [topher-au/WoWmapper#53]
Hello,

I have windows 7, 8Go RAM, Intel I3 dual core (Asus PC portable white) and my pobrleme is the next : 

When i launch the program WoWmapper.exe it's appared in the task bar (little on right) and around 5 seconds left it close itslef and desapear ... i tryed stop Avast protection but it's not working with the firewall it's the same

A solution ?
Cardially, lolo

**Comment by topher-au** [comment]
Hey there, can you try the latest version (7.1.7) and get back to me.
