### ISSUE TITLE
No Wowmapper executable?

### ISSUE THREAD

**Issue by Dnyte270** [topher-au/WoWmapper#63]
I originally tried to install wowmapper as an addon for wow but it didn't work. I watched a couple more videos but it seems like everyone has a program outside of wow.  When I download wowmapper there is no executable file in the zipfile.  I download, unzip, and there is nothing I can run.  What is the name of the executable file and what is the file type?

**Comment by Dissectional** [comment]
WoWmapper_Installer.exe
https://github.com/topher-au/WoWmapper/releases
