### ISSUE TITLE
Antivirus program deletes file

### ISSUE THREAD

**Issue by grimsonia** [topher-au/WoWmapper#71]
My antivirus program deletes the file as a virus?

**Comment by liebig** [comment]
Do you use McAfee? I would suggest to whitelist the files. [Only 3 of 64 virus scanners found a threat.](https://www.virustotal.com/de/file/72ef71b15cd49a08194f7ba87bc92cea4175e916f359b0ba1a3b20f92ed2dbc9/analysis/1502395910/)
