### ISSUE TITLE
Camera view with right stick does not work while streaming with steam

### ISSUE THREAD

**Issue by StephanMcFun** [topher-au/WoWmapper#73]
Hi together,
first of all thanks for your great effort, nice tool.

Currently this is my setup:
PC (running WoW and Steam) -> Laptop (running Steam and WoWmapper + xbox360 controller connected)
WoWmapper runs perfect on PC and on laptop, when I run WoW directly on those machines.

If I stream WoW I cant use camera view with right stick, movement on left stick is fine. I can use the right stick and move mouse cursor but no way when it should act as camera view. 

Do you have any idea what I can try?

Regards,
Stephan

PS: I remapped some buttons, because F12 is screenshot on steam, dont need an image on each cast. :D

**Comment by chancechants** [comment]
I have the same issue. Right analog does not move camera.

**Comment by seblindfors** [comment]
One thing you can try is to switch a conditional in game and then restart the game.
```
/console gxCursor 0
/console gxCursor 1
```
Please note that while we will probably get around to testing Steam streaming at some point, this is not something we officially support as of yet.
