### ISSUE TITLE
Don't use right stick as mouse

### ISSUE THREAD

**Issue by kayakyakr** [topher-au/WoWmapper#78]
I want to be a unique special snowflake (experimenting with touchscreen + 360 controller). WoWmapper is a lovely piece of software but the right stick is emulating the mouse input and the novice in me can't quite find the right thread to pull to get it to map a `GamepadButton.RightStickUp` to, say, `OemComma`.

Currently, giving that mapping blows up everything, so that's been a no-go.

Any suggestions on how to proceed? Can probably get the dev environment set up to hack on this. Maybe. If there's time.

**Comment by seblindfors** [comment]
WoWmapper is designed to be PnP for a very specific purpose. If you want a ton of customization I suggest you find another mapper that lets you do that.

**Comment by seblindfors** [comment]
https://github.com/topher-au/WoWmapper/blob/master/WoWmapper/Controllers/IController.cs#L38-L64

**Comment by kayakyakr** [comment]
:+1: Thanks.
