### ISSUE TITLE
Weird Screen when using L/R 3 (Mouse Click)

### ISSUE THREAD

**Issue by XIII45** [topher-au/WoWmapper#80]
So, when i'm trying to use L3/R3 my screen goes wonky. I've narrowed it down to an issue with Reshade 3.0.
It turns on all of the effects in Reshade at once. I'm just wondering if there's a workaround for this. I couldn't find the settings for L3/R3 anywhere. Wow's looking amazing with ConsolePort, Wowmapper, and Reshade working together,  until i try clicking anything lol.

**Comment by seblindfors** [comment]
This is really something you need to fix with Reshade, not WoWmapper. I would look into Reshade keybindings if I were you.
