### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by hansedbom** [topher-au/WoWmapper#9]
When I open WoWMapper I get some strange popup that says something like "An exception that isn't handled has occured in your software. I can press continue and WoWMapper is opened, when I press "Plugins" I get the same popup but when I press continue nothing happens. I have tried re-installing my .NET framework.
Also someone told me to include the full crash report, I guess this is it: (unfortunately it's in Swedish)

************** Undantagstext **************
System.IO.FileLoadException: Det går inte att läsa in filen eller sammansättningen input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null eller ett av dess beroenden. Åtgärden stöds inte. (Undantag från HRESULT: 0x80131515)
Filnamn: input_360, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null ---> System.NotSupportedException: Ett försök gjordes att läsa in en sammansättning från en nätverksplats som skulle ha försatt sammansättningen i begränsat läge i tidigare versioner av .NET Framework. I den här versionen av .NET Framework är CAS-principen inte aktiverad som standard, så den här inläsningen kan vara farlig. Om den här inläsningen inte är avsedd att försätta sammansättningen i begränsat läge aktiverar du växeln loadFromRemoteSources. Mer information finns på http://go.microsoft.com/fwlink/?LinkId=155569.
   vid System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   vid System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   vid System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   vid WoWmapper.PluginSelectForm.RefreshInputPlugins()
   vid WoWmapper.PluginSelectForm..ctor()
   vid WoWmapper.MainForm.buttonSelectPlugin_Click(Object sender, EventArgs e)
   vid System.Windows.Forms.Control.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   vid System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   vid System.Windows.Forms.Control.WndProc(Message& m)
   vid System.Windows.Forms.ButtonBase.WndProc(Message& m)
   vid System.Windows.Forms.Button.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Inlästa sammansättningar **************
mscorlib
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1063.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WoWmapper
    Sammansättningsversion: 0.4.3.0
    Win32-version: 0.4.3.0
    CodeBase: file:///C:/Users/alfon/Desktop/WoWMapper/WoWmapper.exe
----------------------------------------
System.Windows.Forms
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Sammansättningsversion: 7.0.0.0
    Win32-version: 7.0.1.18622
    CodeBase: file:///C:/Users/alfon/Desktop/WoWMapper/Newtonsoft.Json.DLL
----------------------------------------
WoWmapper_Input
    Sammansättningsversion: 1.0.0.0
    Win32-version: 1.0.0.0
    CodeBase: file:///C:/Users/alfon/Desktop/WoWMapper/WoWmapper_Input.DLL
----------------------------------------
mscorlib.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
WoWmapperEI
    Sammansättningsversion: 0.3.0.0
    Win32-version: 1.0.0.0
    CodeBase: file:///C:/Users/alfon/Desktop/WoWMapper/WoWmapperEI.DLL
----------------------------------------
System.Numerics
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

**Comment by hansedbom** [comment]
Nevermind I reinstalled it again and it worked.

**Comment by topher-au** [comment]
All good! Simply open the plugins folder, right click each of the DLL files
there, go to properties then unblock from the bottom of the properties
window
