### ISSUE TITLE
WoWmapper as a Statusparser?

### ISSUE THREAD

**Issue by Ultra3000** [topher-au/WoWmapper#91]
as i've seen on https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/303828-wowmapper-info-recast-3.html

wowmapper is actually used as a worldparser .. perhaps wowmapper could be used for editing some Things

**Comment by seblindfors** [comment]
Not the same WoWmapper.
