### ISSUE TITLE
New update with 16 point movement causes major issues

### ISSUE THREAD

**Issue by Fr0ntalF8** [topher-au/WoWmapper#99]
Maybe im doing something wrong. But your new update that includes 16 point movement instead of 8 has caused issues to where whenever moving with the left stick, it presses "h",  constantly opening up the pvp window, and "v" constantly turning nameplates on and off. is this normal? is there something i need to do differently?

**Comment by seblindfors** [comment]
Recalibrate ingame

**Comment by Fr0ntalF8** [comment]
thanks for the incredibly quick response!

**Comment by Fr0ntalF8** [comment]
re calibrated controller and its still causing the same issue

**Comment by seblindfors** [comment]
NOTE: This feature requires ConsolePort 1.9.9+ to work properly, otherwise it can be disabled by ticking Analog Inputs > Orthodox movement controls.

**Comment by Fr0ntalF8** [comment]
Im running the latest version on both consoleport and wowmapper

**Comment by seblindfors** [comment]
Please disable the feature. You have custom settings that do not match it. Run default binds in WoWmapper if you want the new features.
